version: "3.8"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile # Dockerfile 이름
    image: ontimedemo # 빌드된 백엔드 이미지
    container_name: ontime-container
    ports:
      - "8080:8080"
      - "8443:8443"
    environment:
      SPRING_CONFIG_ADDITIONAL_LOCATION: file:/etc/ontime/application.properties
      FIREBASE_CREDENTIALS_PATH: /etc/ontime/firebase-adminsdk.json
    volumes:
      - /etc/ontime:/etc/ontime:ro
